### ISSUE TITLE
Failure on Travis

### ISSUE THREAD

**Issue by LeventErkok** [futurice/haskell-futurice-site#15]
Hi.. I'm using this script to run a MacOSX build on Travis. Currently it's failing like this:

   https://travis-ci.org/LeventErkok/sbv/jobs/640591901

(Scroll to the bottom!) It says:

```
Traceback (most recent call last):
  File "<stdin>", line 538, in <module>
  File "<stdin>", line 530, in main
  File "<stdin>", line 507, in executeAliases
  File "<stdin>", line 71, in build
  File "<stdin>", line 151, in build
  File "<stdin>", line 96, in __call__
  File "<stdin>", line 487, in cabalAlias
  File "<stdin>", line 185, in link
  File "<stdin>", line 196, in run
AttributeError: 'module' object has no attribute 'run'
The command "if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update; brew upgrade python; curl https://haskell.futurice.com/haskell-on-macos.py | python - --make-dirs --install-dir=$HOME/.ghc-install --cabal-alias=head install cabal-install-head ${TRAVIS_COMPILER}; fi" failed and exited with 1 during .

```

This started failing perhaps a few weeks ago. I'm not sure what went wrong. (I'm not actually even sure if it's your script that has the problem!) But I'd appreciate if you've any advice as to what might be going wrong.

**Comment by phadej** [comment]
I'm quite sure it's not an issue in the script, as https://github.com/haskell-CI/haskell-ci/blob/7cbffd4076f8c6fd1128b15476cde6badd6ac671/.travis.yml#L72 worked perfectly yesterday.

**Comment by LeventErkok** [comment]
Ah, thanks for that! Comparing with my version, I had an extra:

     brew update; brew upgrade python@3;

inside the `if` statement. (Not sure how it snuck in there in the first place.) Removing that fixed the problem.

Much appreciated.
